// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingester.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createERAPaymentGroup = `-- name: CreateERAPaymentGroup :exec
INSERT INTO era_payment_groups (
    group_id,
    era_id,
    location_id,
    trace_number,
    bpr_amount,
    claim_count,
    claims,
    adjustments,
    status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateERAPaymentGroupParams struct {
	GroupID     string         `json:"group_id"`
	EraID       string         `json:"era_id"`
	LocationID  string         `json:"location_id"`
	TraceNumber string         `json:"trace_number"`
	BprAmount   pgtype.Numeric `json:"bpr_amount"`
	ClaimCount  int32          `json:"claim_count"`
	Claims      []byte         `json:"claims"`
	Adjustments []byte         `json:"adjustments"`
	Status      string         `json:"status"`
}

func (q *Queries) CreateERAPaymentGroup(ctx context.Context, arg CreateERAPaymentGroupParams) error {
	_, err := q.db.Exec(ctx, createERAPaymentGroup,
		arg.GroupID,
		arg.EraID,
		arg.LocationID,
		arg.TraceNumber,
		arg.BprAmount,
		arg.ClaimCount,
		arg.Claims,
		arg.Adjustments,
		arg.Status,
	)
	return err
}

const createERARemittance = `-- name: CreateERARemittance :one
INSERT INTO era_remittances (
    era_id,
    location_id,
    payer_name,
    provider_npi,
    provider_tax_id,
    bpr_amount,
    payment_method,
    trace_number,
    status,
    received_at,
    file_hash,
    raw_storage_key
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING era_id, location_id, payer_name, provider_npi, provider_tax_id, bpr_amount, payment_method, trace_number, status, received_at, file_hash, raw_storage_key, created_at, updated_at
`

type CreateERARemittanceParams struct {
	EraID         string             `json:"era_id"`
	LocationID    string             `json:"location_id"`
	PayerName     pgtype.Text        `json:"payer_name"`
	ProviderNpi   pgtype.Text        `json:"provider_npi"`
	ProviderTaxID pgtype.Text        `json:"provider_tax_id"`
	BprAmount     pgtype.Numeric     `json:"bpr_amount"`
	PaymentMethod pgtype.Text        `json:"payment_method"`
	TraceNumber   pgtype.Text        `json:"trace_number"`
	Status        string             `json:"status"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	FileHash      string             `json:"file_hash"`
	RawStorageKey string             `json:"raw_storage_key"`
}

func (q *Queries) CreateERARemittance(ctx context.Context, arg CreateERARemittanceParams) (EraRemittance, error) {
	row := q.db.QueryRow(ctx, createERARemittance,
		arg.EraID,
		arg.LocationID,
		arg.PayerName,
		arg.ProviderNpi,
		arg.ProviderTaxID,
		arg.BprAmount,
		arg.PaymentMethod,
		arg.TraceNumber,
		arg.Status,
		arg.ReceivedAt,
		arg.FileHash,
		arg.RawStorageKey,
	)
	var i EraRemittance
	err := row.Scan(
		&i.EraID,
		&i.LocationID,
		&i.PayerName,
		&i.ProviderNpi,
		&i.ProviderTaxID,
		&i.BprAmount,
		&i.PaymentMethod,
		&i.TraceNumber,
		&i.Status,
		&i.ReceivedAt,
		&i.FileHash,
		&i.RawStorageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJobRun = `-- name: CreateJobRun :one
INSERT INTO job_runs (
    run_id,
    job_type,
    started_at,
    finished_at,
    status,
    files_processed,
    records_matched,
    errors
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING run_id, job_type, started_at, finished_at, status, files_processed, records_matched, errors, created_at
`

type CreateJobRunParams struct {
	RunID          string             `json:"run_id"`
	JobType        string             `json:"job_type"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Status         string             `json:"status"`
	FilesProcessed int32              `json:"files_processed"`
	RecordsMatched int32              `json:"records_matched"`
	Errors         []byte             `json:"errors"`
}

func (q *Queries) CreateJobRun(ctx context.Context, arg CreateJobRunParams) (JobRun, error) {
	row := q.db.QueryRow(ctx, createJobRun,
		arg.RunID,
		arg.JobType,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Status,
		arg.FilesProcessed,
		arg.RecordsMatched,
		arg.Errors,
	)
	var i JobRun
	err := row.Scan(
		&i.RunID,
		&i.JobType,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.FilesProcessed,
		&i.RecordsMatched,
		&i.Errors,
		&i.CreatedAt,
	)
	return i, err
}

const createVCCFile = `-- name: CreateVCCFile :one
INSERT INTO vcc_files (
    vcc_file_id,
    location_id,
    received_at,
    file_hash,
    raw_storage_key,
    row_count,
    source_filename,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING vcc_file_id, location_id, received_at, file_hash, raw_storage_key, row_count, source_filename, created_at, updated_at, status
`

type CreateVCCFileParams struct {
	VccFileID      string             `json:"vcc_file_id"`
	LocationID     string             `json:"location_id"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	FileHash       string             `json:"file_hash"`
	RawStorageKey  string             `json:"raw_storage_key"`
	RowCount       int32              `json:"row_count"`
	SourceFilename string             `json:"source_filename"`
	Status         string             `json:"status"`
}

func (q *Queries) CreateVCCFile(ctx context.Context, arg CreateVCCFileParams) (VccFile, error) {
	row := q.db.QueryRow(ctx, createVCCFile,
		arg.VccFileID,
		arg.LocationID,
		arg.ReceivedAt,
		arg.FileHash,
		arg.RawStorageKey,
		arg.RowCount,
		arg.SourceFilename,
		arg.Status,
	)
	var i VccFile
	err := row.Scan(
		&i.VccFileID,
		&i.LocationID,
		&i.ReceivedAt,
		&i.FileHash,
		&i.RawStorageKey,
		&i.RowCount,
		&i.SourceFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const createVCCPaymentGroup = `-- name: CreateVCCPaymentGroup :exec
INSERT INTO vcc_payment_groups
    (group_id, vcc_file_id, location_id, trace_id, payment_id, provider_npi, provider_tax_id,
     card_fingerprint, total_amount, status, is_authoritative, payment_method_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateVCCPaymentGroupParams struct {
	GroupID         string         `json:"group_id"`
	VccFileID       string         `json:"vcc_file_id"`
	LocationID      string         `json:"location_id"`
	TraceID         string         `json:"trace_id"`
	PaymentID       string         `json:"payment_id"`
	ProviderNpi     pgtype.Text    `json:"provider_npi"`
	ProviderTaxID   pgtype.Text    `json:"provider_tax_id"`
	CardFingerprint string         `json:"card_fingerprint"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	Status          string         `json:"status"`
	IsAuthoritative bool           `json:"is_authoritative"`
	PaymentMethodID pgtype.Text    `json:"payment_method_id"`
}

func (q *Queries) CreateVCCPaymentGroup(ctx context.Context, arg CreateVCCPaymentGroupParams) error {
	_, err := q.db.Exec(ctx, createVCCPaymentGroup,
		arg.GroupID,
		arg.VccFileID,
		arg.LocationID,
		arg.TraceID,
		arg.PaymentID,
		arg.ProviderNpi,
		arg.ProviderTaxID,
		arg.CardFingerprint,
		arg.TotalAmount,
		arg.Status,
		arg.IsAuthoritative,
		arg.PaymentMethodID,
	)
	return err
}

const getActiveERAPaymentGroup = `-- name: GetActiveERAPaymentGroup :one
SELECT group_id, era_id, location_id, trace_number, bpr_amount::text AS bpr_amount, claim_count, claims,
       adjustments, status,
       reconciliation_triggered_at, created_at
FROM era_payment_groups
WHERE location_id = $1 AND trace_number = $2 AND status NOT IN ('EXCEPTION', 'EXCEPTION_UNMATCHED')
LIMIT 1
`

type GetActiveERAPaymentGroupParams struct {
	LocationID  string `json:"location_id"`
	TraceNumber string `json:"trace_number"`
}

type GetActiveERAPaymentGroupRow struct {
	GroupID                   string             `json:"group_id"`
	EraID                     string             `json:"era_id"`
	LocationID                string             `json:"location_id"`
	TraceNumber               string             `json:"trace_number"`
	BprAmount                 string             `json:"bpr_amount"`
	ClaimCount                int32              `json:"claim_count"`
	Claims                    []byte             `json:"claims"`
	Adjustments               []byte             `json:"adjustments"`
	Status                    string             `json:"status"`
	ReconciliationTriggeredAt pgtype.Timestamptz `json:"reconciliation_triggered_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetActiveERAPaymentGroup(ctx context.Context, arg GetActiveERAPaymentGroupParams) (GetActiveERAPaymentGroupRow, error) {
	row := q.db.QueryRow(ctx, getActiveERAPaymentGroup, arg.LocationID, arg.TraceNumber)
	var i GetActiveERAPaymentGroupRow
	err := row.Scan(
		&i.GroupID,
		&i.EraID,
		&i.LocationID,
		&i.TraceNumber,
		&i.BprAmount,
		&i.ClaimCount,
		&i.Claims,
		&i.Adjustments,
		&i.Status,
		&i.ReconciliationTriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveVCCPaymentGroup = `-- name: GetActiveVCCPaymentGroup :one
SELECT group_id, vcc_file_id, location_id, trace_id, payment_id, provider_npi,
       provider_tax_id, card_fingerprint, total_amount::text AS total_amount, status,
       is_authoritative, reconciliation_triggered_at, created_at
FROM vcc_payment_groups
WHERE location_id = $1 AND trace_id = $2 AND card_fingerprint = $3 AND is_authoritative = true AND status NOT IN ('EXCEPTION', 'EXCEPTION_UNMATCHED')
LIMIT 1
`

type GetActiveVCCPaymentGroupParams struct {
	LocationID      string `json:"location_id"`
	TraceID         string `json:"trace_id"`
	CardFingerprint string `json:"card_fingerprint"`
}

type GetActiveVCCPaymentGroupRow struct {
	GroupID                   string             `json:"group_id"`
	VccFileID                 string             `json:"vcc_file_id"`
	LocationID                string             `json:"location_id"`
	TraceID                   string             `json:"trace_id"`
	PaymentID                 string             `json:"payment_id"`
	ProviderNpi               pgtype.Text        `json:"provider_npi"`
	ProviderTaxID             pgtype.Text        `json:"provider_tax_id"`
	CardFingerprint           string             `json:"card_fingerprint"`
	TotalAmount               string             `json:"total_amount"`
	Status                    string             `json:"status"`
	IsAuthoritative           bool               `json:"is_authoritative"`
	ReconciliationTriggeredAt pgtype.Timestamptz `json:"reconciliation_triggered_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetActiveVCCPaymentGroup(ctx context.Context, arg GetActiveVCCPaymentGroupParams) (GetActiveVCCPaymentGroupRow, error) {
	row := q.db.QueryRow(ctx, getActiveVCCPaymentGroup, arg.LocationID, arg.TraceID, arg.CardFingerprint)
	var i GetActiveVCCPaymentGroupRow
	err := row.Scan(
		&i.GroupID,
		&i.VccFileID,
		&i.LocationID,
		&i.TraceID,
		&i.PaymentID,
		&i.ProviderNpi,
		&i.ProviderTaxID,
		&i.CardFingerprint,
		&i.TotalAmount,
		&i.Status,
		&i.IsAuthoritative,
		&i.ReconciliationTriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getERARemittance = `-- name: GetERARemittance :one
SELECT era_id, location_id, payer_name, provider_npi, provider_tax_id, bpr_amount, payment_method, trace_number, status, received_at, file_hash, raw_storage_key, created_at, updated_at
FROM era_remittances
WHERE era_id = $1
LIMIT 1
`

func (q *Queries) GetERARemittance(ctx context.Context, eraID string) (EraRemittance, error) {
	row := q.db.QueryRow(ctx, getERARemittance, eraID)
	var i EraRemittance
	err := row.Scan(
		&i.EraID,
		&i.LocationID,
		&i.PayerName,
		&i.ProviderNpi,
		&i.ProviderTaxID,
		&i.BprAmount,
		&i.PaymentMethod,
		&i.TraceNumber,
		&i.Status,
		&i.ReceivedAt,
		&i.FileHash,
		&i.RawStorageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getERARemittanceByLocationAndHash = `-- name: GetERARemittanceByLocationAndHash :one
SELECT era_id, location_id, payer_name, provider_npi, provider_tax_id, bpr_amount, payment_method, trace_number, status, received_at, file_hash, raw_storage_key, created_at, updated_at
FROM era_remittances
WHERE location_id = $1
  AND file_hash = $2
LIMIT 1
`

type GetERARemittanceByLocationAndHashParams struct {
	LocationID string `json:"location_id"`
	FileHash   string `json:"file_hash"`
}

func (q *Queries) GetERARemittanceByLocationAndHash(ctx context.Context, arg GetERARemittanceByLocationAndHashParams) (EraRemittance, error) {
	row := q.db.QueryRow(ctx, getERARemittanceByLocationAndHash, arg.LocationID, arg.FileHash)
	var i EraRemittance
	err := row.Scan(
		&i.EraID,
		&i.LocationID,
		&i.PayerName,
		&i.ProviderNpi,
		&i.ProviderTaxID,
		&i.BprAmount,
		&i.PaymentMethod,
		&i.TraceNumber,
		&i.Status,
		&i.ReceivedAt,
		&i.FileHash,
		&i.RawStorageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchingERAForVCC = `-- name: GetMatchingERAForVCC :one
SELECT group_id, era_id, location_id, trace_number, bpr_amount::text AS bpr_amount, claim_count, claims,
       adjustments, status,
       reconciliation_triggered_at, created_at
FROM era_payment_groups
WHERE location_id = $1 AND trace_number = $2 AND status = 'AWAITING_VCC'
LIMIT 1
`

type GetMatchingERAForVCCParams struct {
	LocationID  string `json:"location_id"`
	TraceNumber string `json:"trace_number"`
}

type GetMatchingERAForVCCRow struct {
	GroupID                   string             `json:"group_id"`
	EraID                     string             `json:"era_id"`
	LocationID                string             `json:"location_id"`
	TraceNumber               string             `json:"trace_number"`
	BprAmount                 string             `json:"bpr_amount"`
	ClaimCount                int32              `json:"claim_count"`
	Claims                    []byte             `json:"claims"`
	Adjustments               []byte             `json:"adjustments"`
	Status                    string             `json:"status"`
	ReconciliationTriggeredAt pgtype.Timestamptz `json:"reconciliation_triggered_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMatchingERAForVCC(ctx context.Context, arg GetMatchingERAForVCCParams) (GetMatchingERAForVCCRow, error) {
	row := q.db.QueryRow(ctx, getMatchingERAForVCC, arg.LocationID, arg.TraceNumber)
	var i GetMatchingERAForVCCRow
	err := row.Scan(
		&i.GroupID,
		&i.EraID,
		&i.LocationID,
		&i.TraceNumber,
		&i.BprAmount,
		&i.ClaimCount,
		&i.Claims,
		&i.Adjustments,
		&i.Status,
		&i.ReconciliationTriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchingVCCForERA = `-- name: GetMatchingVCCForERA :one
SELECT group_id, vcc_file_id, location_id, trace_id, payment_id, provider_npi,
       provider_tax_id, card_fingerprint, total_amount::text AS total_amount, status,
       is_authoritative, reconciliation_triggered_at, created_at
FROM vcc_payment_groups
WHERE location_id = $1 AND trace_id = $2 AND status = 'AWAITING_ERA' AND is_authoritative = true
LIMIT 1
`

type GetMatchingVCCForERAParams struct {
	LocationID string `json:"location_id"`
	TraceID    string `json:"trace_id"`
}

type GetMatchingVCCForERARow struct {
	GroupID                   string             `json:"group_id"`
	VccFileID                 string             `json:"vcc_file_id"`
	LocationID                string             `json:"location_id"`
	TraceID                   string             `json:"trace_id"`
	PaymentID                 string             `json:"payment_id"`
	ProviderNpi               pgtype.Text        `json:"provider_npi"`
	ProviderTaxID             pgtype.Text        `json:"provider_tax_id"`
	CardFingerprint           string             `json:"card_fingerprint"`
	TotalAmount               string             `json:"total_amount"`
	Status                    string             `json:"status"`
	IsAuthoritative           bool               `json:"is_authoritative"`
	ReconciliationTriggeredAt pgtype.Timestamptz `json:"reconciliation_triggered_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMatchingVCCForERA(ctx context.Context, arg GetMatchingVCCForERAParams) (GetMatchingVCCForERARow, error) {
	row := q.db.QueryRow(ctx, getMatchingVCCForERA, arg.LocationID, arg.TraceID)
	var i GetMatchingVCCForERARow
	err := row.Scan(
		&i.GroupID,
		&i.VccFileID,
		&i.LocationID,
		&i.TraceID,
		&i.PaymentID,
		&i.ProviderNpi,
		&i.ProviderTaxID,
		&i.CardFingerprint,
		&i.TotalAmount,
		&i.Status,
		&i.IsAuthoritative,
		&i.ReconciliationTriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVCCFile = `-- name: GetVCCFile :one
SELECT vcc_file_id, location_id, received_at, file_hash, raw_storage_key, row_count, source_filename, created_at, updated_at, status
FROM vcc_files
WHERE vcc_file_id = $1
LIMIT 1
`

func (q *Queries) GetVCCFile(ctx context.Context, vccFileID string) (VccFile, error) {
	row := q.db.QueryRow(ctx, getVCCFile, vccFileID)
	var i VccFile
	err := row.Scan(
		&i.VccFileID,
		&i.LocationID,
		&i.ReceivedAt,
		&i.FileHash,
		&i.RawStorageKey,
		&i.RowCount,
		&i.SourceFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getVCCFileByLocationAndHash = `-- name: GetVCCFileByLocationAndHash :one
SELECT vcc_file_id, location_id, received_at, file_hash, raw_storage_key, row_count, source_filename, created_at, updated_at, status
FROM vcc_files
WHERE location_id = $1
  AND file_hash = $2
LIMIT 1
`

type GetVCCFileByLocationAndHashParams struct {
	LocationID string `json:"location_id"`
	FileHash   string `json:"file_hash"`
}

func (q *Queries) GetVCCFileByLocationAndHash(ctx context.Context, arg GetVCCFileByLocationAndHashParams) (VccFile, error) {
	row := q.db.QueryRow(ctx, getVCCFileByLocationAndHash, arg.LocationID, arg.FileHash)
	var i VccFile
	err := row.Scan(
		&i.VccFileID,
		&i.LocationID,
		&i.ReceivedAt,
		&i.FileHash,
		&i.RawStorageKey,
		&i.RowCount,
		&i.SourceFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const insertStateTransition = `-- name: InsertStateTransition :one
INSERT INTO state_transitions (
    transition_id,
    entity_type,
    entity_id,
    from_state,
    to_state,
    transitioned_at,
    reason
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING transition_id, entity_type, entity_id, from_state, to_state, transitioned_at, reason, created_at
`

type InsertStateTransitionParams struct {
	TransitionID   string             `json:"transition_id"`
	EntityType     string             `json:"entity_type"`
	EntityID       string             `json:"entity_id"`
	FromState      pgtype.Text        `json:"from_state"`
	ToState        string             `json:"to_state"`
	TransitionedAt pgtype.Timestamptz `json:"transitioned_at"`
	Reason         pgtype.Text        `json:"reason"`
}

func (q *Queries) InsertStateTransition(ctx context.Context, arg InsertStateTransitionParams) (StateTransition, error) {
	row := q.db.QueryRow(ctx, insertStateTransition,
		arg.TransitionID,
		arg.EntityType,
		arg.EntityID,
		arg.FromState,
		arg.ToState,
		arg.TransitionedAt,
		arg.Reason,
	)
	var i StateTransition
	err := row.Scan(
		&i.TransitionID,
		&i.EntityType,
		&i.EntityID,
		&i.FromState,
		&i.ToState,
		&i.TransitionedAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertVCCRow = `-- name: InsertVCCRow :exec
INSERT INTO vcc_rows
    (row_id, vcc_file_id, vcc_payment_group_id, location_id, payment_id, trace_id,
     payer_name, provider_npi, provider_tax_id, issue_date, amount,
     card_fingerprint, last4, expiration_date, patient_id, claim_id,
     service_date_start, service_date_end)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ON CONFLICT DO NOTHING
`

type InsertVCCRowParams struct {
	RowID             string         `json:"row_id"`
	VccFileID         string         `json:"vcc_file_id"`
	VccPaymentGroupID pgtype.Text    `json:"vcc_payment_group_id"`
	LocationID        string         `json:"location_id"`
	PaymentID         string         `json:"payment_id"`
	TraceID           string         `json:"trace_id"`
	PayerName         pgtype.Text    `json:"payer_name"`
	ProviderNpi       pgtype.Text    `json:"provider_npi"`
	ProviderTaxID     pgtype.Text    `json:"provider_tax_id"`
	IssueDate         pgtype.Date    `json:"issue_date"`
	Amount            pgtype.Numeric `json:"amount"`
	CardFingerprint   string         `json:"card_fingerprint"`
	Last4             string         `json:"last4"`
	ExpirationDate    pgtype.Text    `json:"expiration_date"`
	PatientID         pgtype.Text    `json:"patient_id"`
	ClaimID           pgtype.Text    `json:"claim_id"`
	ServiceDateStart  pgtype.Date    `json:"service_date_start"`
	ServiceDateEnd    pgtype.Date    `json:"service_date_end"`
}

func (q *Queries) InsertVCCRow(ctx context.Context, arg InsertVCCRowParams) error {
	_, err := q.db.Exec(ctx, insertVCCRow,
		arg.RowID,
		arg.VccFileID,
		arg.VccPaymentGroupID,
		arg.LocationID,
		arg.PaymentID,
		arg.TraceID,
		arg.PayerName,
		arg.ProviderNpi,
		arg.ProviderTaxID,
		arg.IssueDate,
		arg.Amount,
		arg.CardFingerprint,
		arg.Last4,
		arg.ExpirationDate,
		arg.PatientID,
		arg.ClaimID,
		arg.ServiceDateStart,
		arg.ServiceDateEnd,
	)
	return err
}

const listERARemittancesByReceivedAt = `-- name: ListERARemittancesByReceivedAt :many
SELECT era_id, location_id, payer_name, provider_npi, provider_tax_id, bpr_amount, payment_method, trace_number, status, received_at, file_hash, raw_storage_key, created_at, updated_at
FROM era_remittances
ORDER BY received_at DESC
LIMIT $1
`

func (q *Queries) ListERARemittancesByReceivedAt(ctx context.Context, limit int32) ([]EraRemittance, error) {
	rows, err := q.db.Query(ctx, listERARemittancesByReceivedAt, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EraRemittance{}
	for rows.Next() {
		var i EraRemittance
		if err := rows.Scan(
			&i.EraID,
			&i.LocationID,
			&i.PayerName,
			&i.ProviderNpi,
			&i.ProviderTaxID,
			&i.BprAmount,
			&i.PaymentMethod,
			&i.TraceNumber,
			&i.Status,
			&i.ReceivedAt,
			&i.FileHash,
			&i.RawStorageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledIngestionTargets = `-- name: ListEnabledIngestionTargets :many
SELECT location_id, provider_npi
FROM location_npi_mappings
WHERE enabled = TRUE
ORDER BY location_id
`

type ListEnabledIngestionTargetsRow struct {
	LocationID  string `json:"location_id"`
	ProviderNpi string `json:"provider_npi"`
}

func (q *Queries) ListEnabledIngestionTargets(ctx context.Context) ([]ListEnabledIngestionTargetsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledIngestionTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledIngestionTargetsRow{}
	for rows.Next() {
		var i ListEnabledIngestionTargetsRow
		if err := rows.Scan(&i.LocationID, &i.ProviderNpi); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledIngestionTargetsForLocation = `-- name: ListEnabledIngestionTargetsForLocation :many
SELECT location_id, provider_npi
FROM location_npi_mappings
WHERE enabled = TRUE
    AND location_id = $1
ORDER BY location_id
`

type ListEnabledIngestionTargetsForLocationRow struct {
	LocationID  string `json:"location_id"`
	ProviderNpi string `json:"provider_npi"`
}

func (q *Queries) ListEnabledIngestionTargetsForLocation(ctx context.Context, locationID string) ([]ListEnabledIngestionTargetsForLocationRow, error) {
	rows, err := q.db.Query(ctx, listEnabledIngestionTargetsForLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledIngestionTargetsForLocationRow{}
	for rows.Next() {
		var i ListEnabledIngestionTargetsForLocationRow
		if err := rows.Scan(&i.LocationID, &i.ProviderNpi); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markERAReconciliationTriggered = `-- name: MarkERAReconciliationTriggered :exec
UPDATE era_payment_groups SET reconciliation_triggered_at = NOW(), updated_at = NOW() WHERE group_id = $1
`

func (q *Queries) MarkERAReconciliationTriggered(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, markERAReconciliationTriggered, groupID)
	return err
}

const markVCCGroupNonAuthoritative = `-- name: MarkVCCGroupNonAuthoritative :exec
UPDATE vcc_payment_groups SET is_authoritative = false, updated_at = NOW() WHERE group_id = $1
`

func (q *Queries) MarkVCCGroupNonAuthoritative(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, markVCCGroupNonAuthoritative, groupID)
	return err
}

const markVCCReconciliationTriggered = `-- name: MarkVCCReconciliationTriggered :exec
UPDATE vcc_payment_groups SET reconciliation_triggered_at = NOW(), updated_at = NOW() WHERE group_id = $1
`

func (q *Queries) MarkVCCReconciliationTriggered(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, markVCCReconciliationTriggered, groupID)
	return err
}

const setERAPaymentGroupException = `-- name: SetERAPaymentGroupException :exec
UPDATE era_payment_groups SET status = 'EXCEPTION', updated_at = NOW() WHERE group_id = $1
`

func (q *Queries) SetERAPaymentGroupException(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, setERAPaymentGroupException, groupID)
	return err
}

const setERARemittanceParseFailure = `-- name: SetERARemittanceParseFailure :exec
UPDATE era_remittances
SET status = 'EXCEPTION_PARSE_FAILED',
    updated_at = NOW()
WHERE era_id = $1
`

func (q *Queries) SetERARemittanceParseFailure(ctx context.Context, eraID string) error {
	_, err := q.db.Exec(ctx, setERARemittanceParseFailure, eraID)
	return err
}

const setVCCFileParseFailure = `-- name: SetVCCFileParseFailure :exec
UPDATE vcc_files
SET row_count = $2,
    status = 'EXCEPTION_PARSE_FAILED',
    updated_at = NOW()
WHERE vcc_file_id = $1
`

type SetVCCFileParseFailureParams struct {
	VccFileID string `json:"vcc_file_id"`
	RowCount  int32  `json:"row_count"`
}

func (q *Queries) SetVCCFileParseFailure(ctx context.Context, arg SetVCCFileParseFailureParams) error {
	_, err := q.db.Exec(ctx, setVCCFileParseFailure, arg.VccFileID, arg.RowCount)
	return err
}

const setVCCPaymentGroupException = `-- name: SetVCCPaymentGroupException :exec
UPDATE vcc_payment_groups SET status = 'EXCEPTION', updated_at = NOW() WHERE group_id = $1
`

func (q *Queries) SetVCCPaymentGroupException(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, setVCCPaymentGroupException, groupID)
	return err
}

const updateERARemittanceParsed = `-- name: UpdateERARemittanceParsed :exec
UPDATE era_remittances
SET payer_name = $2,
    provider_npi = $3,
    provider_tax_id = $4,
    bpr_amount = $5,
    payment_method = $6,
    trace_number = $7,
    status = 'PARSED',
    updated_at = NOW()
WHERE era_id = $1
`

type UpdateERARemittanceParsedParams struct {
	EraID         string         `json:"era_id"`
	PayerName     pgtype.Text    `json:"payer_name"`
	ProviderNpi   pgtype.Text    `json:"provider_npi"`
	ProviderTaxID pgtype.Text    `json:"provider_tax_id"`
	BprAmount     pgtype.Numeric `json:"bpr_amount"`
	PaymentMethod pgtype.Text    `json:"payment_method"`
	TraceNumber   pgtype.Text    `json:"trace_number"`
}

func (q *Queries) UpdateERARemittanceParsed(ctx context.Context, arg UpdateERARemittanceParsedParams) error {
	_, err := q.db.Exec(ctx, updateERARemittanceParsed,
		arg.EraID,
		arg.PayerName,
		arg.ProviderNpi,
		arg.ProviderTaxID,
		arg.BprAmount,
		arg.PaymentMethod,
		arg.TraceNumber,
	)
	return err
}

const updateJobRunResult = `-- name: UpdateJobRunResult :exec
UPDATE job_runs
SET finished_at = $2,
    status = $3,
    files_processed = $4,
    records_matched = $5,
    errors = $6
WHERE run_id = $1
`

type UpdateJobRunResultParams struct {
	RunID          string             `json:"run_id"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Status         string             `json:"status"`
	FilesProcessed int32              `json:"files_processed"`
	RecordsMatched int32              `json:"records_matched"`
	Errors         []byte             `json:"errors"`
}

func (q *Queries) UpdateJobRunResult(ctx context.Context, arg UpdateJobRunResultParams) error {
	_, err := q.db.Exec(ctx, updateJobRunResult,
		arg.RunID,
		arg.FinishedAt,
		arg.Status,
		arg.FilesProcessed,
		arg.RecordsMatched,
		arg.Errors,
	)
	return err
}

const updateVCCFileParsed = `-- name: UpdateVCCFileParsed :exec
UPDATE vcc_files
SET row_count = $2,
    status = 'PARSED',
    updated_at = NOW()
WHERE vcc_file_id = $1
`

type UpdateVCCFileParsedParams struct {
	VccFileID string `json:"vcc_file_id"`
	RowCount  int32  `json:"row_count"`
}

func (q *Queries) UpdateVCCFileParsed(ctx context.Context, arg UpdateVCCFileParsedParams) error {
	_, err := q.db.Exec(ctx, updateVCCFileParsed, arg.VccFileID, arg.RowCount)
	return err
}
