// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciler.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReconciledPayment = `-- name: CreateReconciledPayment :one
INSERT INTO reconciled_payments (
    reconciled_payment_id,
    location_id,
    era_payment_group_id,
    vcc_payment_group_id,
    trace_number,
    matched_amount,
    payer_name,
    provider_npi,
    provider_tax_id,
    status,
    matched_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING
    reconciled_payment_id,
    location_id,
    era_payment_group_id,
    vcc_payment_group_id,
    trace_number,
    matched_amount,
    payer_name,
    provider_npi,
    provider_tax_id,
    status,
    matched_at,
    created_at,
    updated_at
`

type CreateReconciledPaymentParams struct {
	ReconciledPaymentID string             `json:"reconciled_payment_id"`
	LocationID          string             `json:"location_id"`
	EraPaymentGroupID   string             `json:"era_payment_group_id"`
	VccPaymentGroupID   string             `json:"vcc_payment_group_id"`
	TraceNumber         string             `json:"trace_number"`
	MatchedAmount       pgtype.Numeric     `json:"matched_amount"`
	PayerName           pgtype.Text        `json:"payer_name"`
	ProviderNpi         pgtype.Text        `json:"provider_npi"`
	ProviderTaxID       pgtype.Text        `json:"provider_tax_id"`
	Status              string             `json:"status"`
	MatchedAt           pgtype.Timestamptz `json:"matched_at"`
}

type CreateReconciledPaymentRow struct {
	ReconciledPaymentID string             `json:"reconciled_payment_id"`
	LocationID          string             `json:"location_id"`
	EraPaymentGroupID   string             `json:"era_payment_group_id"`
	VccPaymentGroupID   string             `json:"vcc_payment_group_id"`
	TraceNumber         string             `json:"trace_number"`
	MatchedAmount       pgtype.Numeric     `json:"matched_amount"`
	PayerName           pgtype.Text        `json:"payer_name"`
	ProviderNpi         pgtype.Text        `json:"provider_npi"`
	ProviderTaxID       pgtype.Text        `json:"provider_tax_id"`
	Status              string             `json:"status"`
	MatchedAt           pgtype.Timestamptz `json:"matched_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateReconciledPayment(ctx context.Context, arg CreateReconciledPaymentParams) (CreateReconciledPaymentRow, error) {
	row := q.db.QueryRow(ctx, createReconciledPayment,
		arg.ReconciledPaymentID,
		arg.LocationID,
		arg.EraPaymentGroupID,
		arg.VccPaymentGroupID,
		arg.TraceNumber,
		arg.MatchedAmount,
		arg.PayerName,
		arg.ProviderNpi,
		arg.ProviderTaxID,
		arg.Status,
		arg.MatchedAt,
	)
	var i CreateReconciledPaymentRow
	err := row.Scan(
		&i.ReconciledPaymentID,
		&i.LocationID,
		&i.EraPaymentGroupID,
		&i.VccPaymentGroupID,
		&i.TraceNumber,
		&i.MatchedAmount,
		&i.PayerName,
		&i.ProviderNpi,
		&i.ProviderTaxID,
		&i.Status,
		&i.MatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReconcilerJobRun = `-- name: CreateReconcilerJobRun :one
INSERT INTO job_runs (
    run_id,
    job_type,
    started_at,
    finished_at,
    status,
    files_processed,
    records_matched,
    errors
) VALUES (
    $1,
    'reconciler',
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING run_id, job_type, started_at, finished_at, status, files_processed, records_matched, errors, created_at
`

type CreateReconcilerJobRunParams struct {
	RunID          string             `json:"run_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Status         string             `json:"status"`
	FilesProcessed int32              `json:"files_processed"`
	RecordsMatched int32              `json:"records_matched"`
	Errors         []byte             `json:"errors"`
}

func (q *Queries) CreateReconcilerJobRun(ctx context.Context, arg CreateReconcilerJobRunParams) (JobRun, error) {
	row := q.db.QueryRow(ctx, createReconcilerJobRun,
		arg.RunID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Status,
		arg.FilesProcessed,
		arg.RecordsMatched,
		arg.Errors,
	)
	var i JobRun
	err := row.Scan(
		&i.RunID,
		&i.JobType,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.FilesProcessed,
		&i.RecordsMatched,
		&i.Errors,
		&i.CreatedAt,
	)
	return i, err
}

const expireUnmatchedERAPaymentGroup = `-- name: ExpireUnmatchedERAPaymentGroup :one
UPDATE era_payment_groups
SET prior_status = status,
    status = 'EXCEPTION_UNMATCHED',
    exception_at = $2,
    exception_reason = $3,
    updated_at = $2
WHERE group_id = $1
  AND status = 'AWAITING_VCC'
RETURNING group_id, prior_status, status, exception_at, exception_reason
`

type ExpireUnmatchedERAPaymentGroupParams struct {
	GroupID         string             `json:"group_id"`
	ExceptionAt     pgtype.Timestamptz `json:"exception_at"`
	ExceptionReason pgtype.Text        `json:"exception_reason"`
}

type ExpireUnmatchedERAPaymentGroupRow struct {
	GroupID         string             `json:"group_id"`
	PriorStatus     pgtype.Text        `json:"prior_status"`
	Status          string             `json:"status"`
	ExceptionAt     pgtype.Timestamptz `json:"exception_at"`
	ExceptionReason pgtype.Text        `json:"exception_reason"`
}

func (q *Queries) ExpireUnmatchedERAPaymentGroup(ctx context.Context, arg ExpireUnmatchedERAPaymentGroupParams) (ExpireUnmatchedERAPaymentGroupRow, error) {
	row := q.db.QueryRow(ctx, expireUnmatchedERAPaymentGroup, arg.GroupID, arg.ExceptionAt, arg.ExceptionReason)
	var i ExpireUnmatchedERAPaymentGroupRow
	err := row.Scan(
		&i.GroupID,
		&i.PriorStatus,
		&i.Status,
		&i.ExceptionAt,
		&i.ExceptionReason,
	)
	return i, err
}

const expireUnmatchedVCCPaymentGroup = `-- name: ExpireUnmatchedVCCPaymentGroup :one
UPDATE vcc_payment_groups
SET prior_status = status,
    status = 'EXCEPTION_UNMATCHED',
    exception_at = $2,
    exception_reason = $3,
    updated_at = $2
WHERE group_id = $1
  AND status = 'AWAITING_ERA'
RETURNING group_id, prior_status, status, exception_at, exception_reason
`

type ExpireUnmatchedVCCPaymentGroupParams struct {
	GroupID         string             `json:"group_id"`
	ExceptionAt     pgtype.Timestamptz `json:"exception_at"`
	ExceptionReason pgtype.Text        `json:"exception_reason"`
}

type ExpireUnmatchedVCCPaymentGroupRow struct {
	GroupID         string             `json:"group_id"`
	PriorStatus     pgtype.Text        `json:"prior_status"`
	Status          string             `json:"status"`
	ExceptionAt     pgtype.Timestamptz `json:"exception_at"`
	ExceptionReason pgtype.Text        `json:"exception_reason"`
}

func (q *Queries) ExpireUnmatchedVCCPaymentGroup(ctx context.Context, arg ExpireUnmatchedVCCPaymentGroupParams) (ExpireUnmatchedVCCPaymentGroupRow, error) {
	row := q.db.QueryRow(ctx, expireUnmatchedVCCPaymentGroup, arg.GroupID, arg.ExceptionAt, arg.ExceptionReason)
	var i ExpireUnmatchedVCCPaymentGroupRow
	err := row.Scan(
		&i.GroupID,
		&i.PriorStatus,
		&i.Status,
		&i.ExceptionAt,
		&i.ExceptionReason,
	)
	return i, err
}

const insertReconcilerStateTransition = `-- name: InsertReconcilerStateTransition :one
INSERT INTO state_transitions (
    transition_id,
    entity_type,
    entity_id,
    from_state,
    to_state,
    transitioned_at,
    reason
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING transition_id, entity_type, entity_id, from_state, to_state, transitioned_at, reason, created_at
`

type InsertReconcilerStateTransitionParams struct {
	TransitionID   string             `json:"transition_id"`
	EntityType     string             `json:"entity_type"`
	EntityID       string             `json:"entity_id"`
	FromState      pgtype.Text        `json:"from_state"`
	ToState        string             `json:"to_state"`
	TransitionedAt pgtype.Timestamptz `json:"transitioned_at"`
	Reason         pgtype.Text        `json:"reason"`
}

func (q *Queries) InsertReconcilerStateTransition(ctx context.Context, arg InsertReconcilerStateTransitionParams) (StateTransition, error) {
	row := q.db.QueryRow(ctx, insertReconcilerStateTransition,
		arg.TransitionID,
		arg.EntityType,
		arg.EntityID,
		arg.FromState,
		arg.ToState,
		arg.TransitionedAt,
		arg.Reason,
	)
	var i StateTransition
	err := row.Scan(
		&i.TransitionID,
		&i.EntityType,
		&i.EntityID,
		&i.FromState,
		&i.ToState,
		&i.TransitionedAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listERACounterpartCandidates = `-- name: ListERACounterpartCandidates :many
SELECT
    epg.group_id,
    epg.era_id,
    epg.location_id,
    epg.trace_number,
    epg.bpr_amount::text AS bpr_amount,
    epg.status,
    epg.reconciliation_triggered_at,
    epg.created_at,
    epg.updated_at,
    epg.first_received_at,
    epg.matched_at,
    epg.exception_at,
    epg.prior_status,
    epg.exception_reason,
    er.payer_name,
    er.provider_npi,
    er.provider_tax_id
FROM era_payment_groups epg
JOIN era_remittances er ON er.era_id = epg.era_id
WHERE epg.location_id = $1
  AND epg.trace_number = $2
  AND epg.status = 'AWAITING_VCC'
ORDER BY epg.first_received_at ASC, epg.group_id ASC
`

type ListERACounterpartCandidatesParams struct {
	LocationID  string `json:"location_id"`
	TraceNumber string `json:"trace_number"`
}

type ListERACounterpartCandidatesRow struct {
	GroupID                   string             `json:"group_id"`
	EraID                     string             `json:"era_id"`
	LocationID                string             `json:"location_id"`
	TraceNumber               string             `json:"trace_number"`
	BprAmount                 string             `json:"bpr_amount"`
	Status                    string             `json:"status"`
	ReconciliationTriggeredAt pgtype.Timestamptz `json:"reconciliation_triggered_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	FirstReceivedAt           pgtype.Timestamptz `json:"first_received_at"`
	MatchedAt                 pgtype.Timestamptz `json:"matched_at"`
	ExceptionAt               pgtype.Timestamptz `json:"exception_at"`
	PriorStatus               pgtype.Text        `json:"prior_status"`
	ExceptionReason           pgtype.Text        `json:"exception_reason"`
	PayerName                 pgtype.Text        `json:"payer_name"`
	ProviderNpi               pgtype.Text        `json:"provider_npi"`
	ProviderTaxID             pgtype.Text        `json:"provider_tax_id"`
}

func (q *Queries) ListERACounterpartCandidates(ctx context.Context, arg ListERACounterpartCandidatesParams) ([]ListERACounterpartCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listERACounterpartCandidates, arg.LocationID, arg.TraceNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListERACounterpartCandidatesRow{}
	for rows.Next() {
		var i ListERACounterpartCandidatesRow
		if err := rows.Scan(
			&i.GroupID,
			&i.EraID,
			&i.LocationID,
			&i.TraceNumber,
			&i.BprAmount,
			&i.Status,
			&i.ReconciliationTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstReceivedAt,
			&i.MatchedAt,
			&i.ExceptionAt,
			&i.PriorStatus,
			&i.ExceptionReason,
			&i.PayerName,
			&i.ProviderNpi,
			&i.ProviderTaxID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmatchedERAPaymentGroups = `-- name: ListUnmatchedERAPaymentGroups :many
SELECT
    epg.group_id,
    epg.era_id,
    epg.location_id,
    epg.trace_number,
    epg.bpr_amount::text AS bpr_amount,
    epg.status,
    epg.reconciliation_triggered_at,
    epg.created_at,
    epg.updated_at,
    epg.first_received_at,
    epg.matched_at,
    epg.exception_at,
    epg.prior_status,
    epg.exception_reason,
    er.payer_name,
    er.provider_npi,
    er.provider_tax_id
FROM era_payment_groups epg
JOIN era_remittances er ON er.era_id = epg.era_id
WHERE epg.status = 'AWAITING_VCC'
ORDER BY epg.first_received_at ASC, epg.group_id ASC
`

type ListUnmatchedERAPaymentGroupsRow struct {
	GroupID                   string             `json:"group_id"`
	EraID                     string             `json:"era_id"`
	LocationID                string             `json:"location_id"`
	TraceNumber               string             `json:"trace_number"`
	BprAmount                 string             `json:"bpr_amount"`
	Status                    string             `json:"status"`
	ReconciliationTriggeredAt pgtype.Timestamptz `json:"reconciliation_triggered_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	FirstReceivedAt           pgtype.Timestamptz `json:"first_received_at"`
	MatchedAt                 pgtype.Timestamptz `json:"matched_at"`
	ExceptionAt               pgtype.Timestamptz `json:"exception_at"`
	PriorStatus               pgtype.Text        `json:"prior_status"`
	ExceptionReason           pgtype.Text        `json:"exception_reason"`
	PayerName                 pgtype.Text        `json:"payer_name"`
	ProviderNpi               pgtype.Text        `json:"provider_npi"`
	ProviderTaxID             pgtype.Text        `json:"provider_tax_id"`
}

func (q *Queries) ListUnmatchedERAPaymentGroups(ctx context.Context) ([]ListUnmatchedERAPaymentGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUnmatchedERAPaymentGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnmatchedERAPaymentGroupsRow{}
	for rows.Next() {
		var i ListUnmatchedERAPaymentGroupsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.EraID,
			&i.LocationID,
			&i.TraceNumber,
			&i.BprAmount,
			&i.Status,
			&i.ReconciliationTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstReceivedAt,
			&i.MatchedAt,
			&i.ExceptionAt,
			&i.PriorStatus,
			&i.ExceptionReason,
			&i.PayerName,
			&i.ProviderNpi,
			&i.ProviderTaxID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmatchedVCCPaymentGroups = `-- name: ListUnmatchedVCCPaymentGroups :many
SELECT
    group_id,
    vcc_file_id,
    location_id,
    trace_id,
    payment_id,
    provider_npi,
    provider_tax_id,
    card_fingerprint,
    total_amount::text AS total_amount,
    status,
    is_authoritative,
    reconciliation_triggered_at,
    created_at,
    updated_at,
    first_received_at,
    matched_at,
    exception_at,
    prior_status,
    exception_reason
FROM vcc_payment_groups
WHERE status = 'AWAITING_ERA'
  AND is_authoritative = TRUE
ORDER BY first_received_at ASC, group_id ASC
`

type ListUnmatchedVCCPaymentGroupsRow struct {
	GroupID                   string             `json:"group_id"`
	VccFileID                 string             `json:"vcc_file_id"`
	LocationID                string             `json:"location_id"`
	TraceID                   string             `json:"trace_id"`
	PaymentID                 string             `json:"payment_id"`
	ProviderNpi               pgtype.Text        `json:"provider_npi"`
	ProviderTaxID             pgtype.Text        `json:"provider_tax_id"`
	CardFingerprint           string             `json:"card_fingerprint"`
	TotalAmount               string             `json:"total_amount"`
	Status                    string             `json:"status"`
	IsAuthoritative           bool               `json:"is_authoritative"`
	ReconciliationTriggeredAt pgtype.Timestamptz `json:"reconciliation_triggered_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	FirstReceivedAt           pgtype.Timestamptz `json:"first_received_at"`
	MatchedAt                 pgtype.Timestamptz `json:"matched_at"`
	ExceptionAt               pgtype.Timestamptz `json:"exception_at"`
	PriorStatus               pgtype.Text        `json:"prior_status"`
	ExceptionReason           pgtype.Text        `json:"exception_reason"`
}

func (q *Queries) ListUnmatchedVCCPaymentGroups(ctx context.Context) ([]ListUnmatchedVCCPaymentGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUnmatchedVCCPaymentGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnmatchedVCCPaymentGroupsRow{}
	for rows.Next() {
		var i ListUnmatchedVCCPaymentGroupsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.VccFileID,
			&i.LocationID,
			&i.TraceID,
			&i.PaymentID,
			&i.ProviderNpi,
			&i.ProviderTaxID,
			&i.CardFingerprint,
			&i.TotalAmount,
			&i.Status,
			&i.IsAuthoritative,
			&i.ReconciliationTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstReceivedAt,
			&i.MatchedAt,
			&i.ExceptionAt,
			&i.PriorStatus,
			&i.ExceptionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVCCCounterpartCandidates = `-- name: ListVCCCounterpartCandidates :many
SELECT
    group_id,
    vcc_file_id,
    location_id,
    trace_id,
    payment_id,
    provider_npi,
    provider_tax_id,
    card_fingerprint,
    total_amount::text AS total_amount,
    status,
    is_authoritative,
    reconciliation_triggered_at,
    created_at,
    updated_at,
    first_received_at,
    matched_at,
    exception_at,
    prior_status,
    exception_reason
FROM vcc_payment_groups
WHERE location_id = $1
  AND trace_id = $2
  AND status = 'AWAITING_ERA'
  AND is_authoritative = TRUE
ORDER BY first_received_at ASC, group_id ASC
`

type ListVCCCounterpartCandidatesParams struct {
	LocationID string `json:"location_id"`
	TraceID    string `json:"trace_id"`
}

type ListVCCCounterpartCandidatesRow struct {
	GroupID                   string             `json:"group_id"`
	VccFileID                 string             `json:"vcc_file_id"`
	LocationID                string             `json:"location_id"`
	TraceID                   string             `json:"trace_id"`
	PaymentID                 string             `json:"payment_id"`
	ProviderNpi               pgtype.Text        `json:"provider_npi"`
	ProviderTaxID             pgtype.Text        `json:"provider_tax_id"`
	CardFingerprint           string             `json:"card_fingerprint"`
	TotalAmount               string             `json:"total_amount"`
	Status                    string             `json:"status"`
	IsAuthoritative           bool               `json:"is_authoritative"`
	ReconciliationTriggeredAt pgtype.Timestamptz `json:"reconciliation_triggered_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	FirstReceivedAt           pgtype.Timestamptz `json:"first_received_at"`
	MatchedAt                 pgtype.Timestamptz `json:"matched_at"`
	ExceptionAt               pgtype.Timestamptz `json:"exception_at"`
	PriorStatus               pgtype.Text        `json:"prior_status"`
	ExceptionReason           pgtype.Text        `json:"exception_reason"`
}

func (q *Queries) ListVCCCounterpartCandidates(ctx context.Context, arg ListVCCCounterpartCandidatesParams) ([]ListVCCCounterpartCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listVCCCounterpartCandidates, arg.LocationID, arg.TraceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVCCCounterpartCandidatesRow{}
	for rows.Next() {
		var i ListVCCCounterpartCandidatesRow
		if err := rows.Scan(
			&i.GroupID,
			&i.VccFileID,
			&i.LocationID,
			&i.TraceID,
			&i.PaymentID,
			&i.ProviderNpi,
			&i.ProviderTaxID,
			&i.CardFingerprint,
			&i.TotalAmount,
			&i.Status,
			&i.IsAuthoritative,
			&i.ReconciliationTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstReceivedAt,
			&i.MatchedAt,
			&i.ExceptionAt,
			&i.PriorStatus,
			&i.ExceptionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markERAPaymentGroupMatched = `-- name: MarkERAPaymentGroupMatched :one
UPDATE era_payment_groups
SET status = 'MATCHED',
    matched_at = $2,
    updated_at = $2
WHERE group_id = $1
  AND status = 'AWAITING_VCC'
RETURNING group_id, status, matched_at
`

type MarkERAPaymentGroupMatchedParams struct {
	GroupID   string             `json:"group_id"`
	MatchedAt pgtype.Timestamptz `json:"matched_at"`
}

type MarkERAPaymentGroupMatchedRow struct {
	GroupID   string             `json:"group_id"`
	Status    string             `json:"status"`
	MatchedAt pgtype.Timestamptz `json:"matched_at"`
}

func (q *Queries) MarkERAPaymentGroupMatched(ctx context.Context, arg MarkERAPaymentGroupMatchedParams) (MarkERAPaymentGroupMatchedRow, error) {
	row := q.db.QueryRow(ctx, markERAPaymentGroupMatched, arg.GroupID, arg.MatchedAt)
	var i MarkERAPaymentGroupMatchedRow
	err := row.Scan(&i.GroupID, &i.Status, &i.MatchedAt)
	return i, err
}

const markVCCPaymentGroupMatched = `-- name: MarkVCCPaymentGroupMatched :one
UPDATE vcc_payment_groups
SET status = 'MATCHED',
    matched_at = $2,
    updated_at = $2
WHERE group_id = $1
  AND status = 'AWAITING_ERA'
RETURNING group_id, status, matched_at
`

type MarkVCCPaymentGroupMatchedParams struct {
	GroupID   string             `json:"group_id"`
	MatchedAt pgtype.Timestamptz `json:"matched_at"`
}

type MarkVCCPaymentGroupMatchedRow struct {
	GroupID   string             `json:"group_id"`
	Status    string             `json:"status"`
	MatchedAt pgtype.Timestamptz `json:"matched_at"`
}

func (q *Queries) MarkVCCPaymentGroupMatched(ctx context.Context, arg MarkVCCPaymentGroupMatchedParams) (MarkVCCPaymentGroupMatchedRow, error) {
	row := q.db.QueryRow(ctx, markVCCPaymentGroupMatched, arg.GroupID, arg.MatchedAt)
	var i MarkVCCPaymentGroupMatchedRow
	err := row.Scan(&i.GroupID, &i.Status, &i.MatchedAt)
	return i, err
}

const notifyReconciledPaymentMatched = `-- name: NotifyReconciledPaymentMatched :exec
SELECT pg_notify('reconciled_payment_matched', $1)
`

func (q *Queries) NotifyReconciledPaymentMatched(ctx context.Context, pgNotify string) error {
	_, err := q.db.Exec(ctx, notifyReconciledPaymentMatched, pgNotify)
	return err
}

const updateReconcilerJobRunResult = `-- name: UpdateReconcilerJobRunResult :exec
UPDATE job_runs
SET finished_at = $2,
    status = $3,
    files_processed = $4,
    records_matched = $5,
    errors = $6
WHERE run_id = $1
  AND job_type = 'reconciler'
`

type UpdateReconcilerJobRunResultParams struct {
	RunID          string             `json:"run_id"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Status         string             `json:"status"`
	FilesProcessed int32              `json:"files_processed"`
	RecordsMatched int32              `json:"records_matched"`
	Errors         []byte             `json:"errors"`
}

func (q *Queries) UpdateReconcilerJobRunResult(ctx context.Context, arg UpdateReconcilerJobRunResultParams) error {
	_, err := q.db.Exec(ctx, updateReconcilerJobRunResult,
		arg.RunID,
		arg.FinishedAt,
		arg.Status,
		arg.FilesProcessed,
		arg.RecordsMatched,
		arg.Errors,
	)
	return err
}
