-- +goose Up
ALTER TABLE vcc_files
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'RECEIVED_RAW'
    CHECK (status IN ('RECEIVED_RAW', 'PARSED', 'EXCEPTION_PARSE_FAILED'));

ALTER TABLE era_payment_groups
    ADD COLUMN IF NOT EXISTS claim_count INTEGER NOT NULL DEFAULT 0 CHECK (claim_count >= 0),
    ADD COLUMN IF NOT EXISTS claims JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS adjustments JSONB NOT NULL DEFAULT '[]'::jsonb;
