// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EraPaymentGroup struct {
	GroupID                   string             `json:"group_id"`
	EraID                     string             `json:"era_id"`
	LocationID                string             `json:"location_id"`
	TraceNumber               string             `json:"trace_number"`
	BprAmount                 pgtype.Numeric     `json:"bpr_amount"`
	Status                    string             `json:"status"`
	ReconciliationTriggeredAt pgtype.Timestamptz `json:"reconciliation_triggered_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	ClaimCount                int32              `json:"claim_count"`
	Claims                    []byte             `json:"claims"`
	Adjustments               []byte             `json:"adjustments"`
	FirstReceivedAt           pgtype.Timestamptz `json:"first_received_at"`
	MatchedAt                 pgtype.Timestamptz `json:"matched_at"`
	ExceptionAt               pgtype.Timestamptz `json:"exception_at"`
	PriorStatus               pgtype.Text        `json:"prior_status"`
	ExceptionReason           pgtype.Text        `json:"exception_reason"`
}

type EraRemittance struct {
	EraID         string             `json:"era_id"`
	LocationID    string             `json:"location_id"`
	PayerName     pgtype.Text        `json:"payer_name"`
	ProviderNpi   pgtype.Text        `json:"provider_npi"`
	ProviderTaxID pgtype.Text        `json:"provider_tax_id"`
	BprAmount     pgtype.Numeric     `json:"bpr_amount"`
	PaymentMethod pgtype.Text        `json:"payment_method"`
	TraceNumber   pgtype.Text        `json:"trace_number"`
	Status        string             `json:"status"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	FileHash      string             `json:"file_hash"`
	RawStorageKey string             `json:"raw_storage_key"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type JobRun struct {
	RunID          string             `json:"run_id"`
	JobType        string             `json:"job_type"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Status         string             `json:"status"`
	FilesProcessed int32              `json:"files_processed"`
	RecordsMatched int32              `json:"records_matched"`
	Errors         []byte             `json:"errors"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type LocationNpiMapping struct {
	LocationID  string             `json:"location_id"`
	ProviderNpi string             `json:"provider_npi"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProcessorAttempt struct {
	AttemptID           string             `json:"attempt_id"`
	ReconciledPaymentID string             `json:"reconciled_payment_id"`
	IdempotencyKey      string             `json:"idempotency_key"`
	AttemptNumber       int32              `json:"attempt_number"`
	Outcome             string             `json:"outcome"`
	ErrorCode           pgtype.Text        `json:"error_code"`
	ErrorMessage        pgtype.Text        `json:"error_message"`
	AttemptedAt         pgtype.Timestamptz `json:"attempted_at"`
}

type ReconciledPayment struct {
	ReconciledPaymentID      string             `json:"reconciled_payment_id"`
	LocationID               string             `json:"location_id"`
	EraPaymentGroupID        string             `json:"era_payment_group_id"`
	VccPaymentGroupID        string             `json:"vcc_payment_group_id"`
	TraceNumber              string             `json:"trace_number"`
	MatchedAmount            pgtype.Numeric     `json:"matched_amount"`
	PayerName                pgtype.Text        `json:"payer_name"`
	ProviderNpi              pgtype.Text        `json:"provider_npi"`
	ProviderTaxID            pgtype.Text        `json:"provider_tax_id"`
	Status                   string             `json:"status"`
	MatchedAt                pgtype.Timestamptz `json:"matched_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	IdempotencyKey           pgtype.Text        `json:"idempotency_key"`
	ProcessorPaymentIntentID pgtype.Text        `json:"processor_payment_intent_id"`
	ProcessorChargeID        pgtype.Text        `json:"processor_charge_id"`
	ProcessorErrorCode       pgtype.Text        `json:"processor_error_code"`
	ProcessorErrorMessage    pgtype.Text        `json:"processor_error_message"`
	ProcessingStartedAt      pgtype.Timestamptz `json:"processing_started_at"`
	ProcessingCompletedAt    pgtype.Timestamptz `json:"processing_completed_at"`
	RetryCount               int32              `json:"retry_count"`
}

type StateTransition struct {
	TransitionID   string             `json:"transition_id"`
	EntityType     string             `json:"entity_type"`
	EntityID       string             `json:"entity_id"`
	FromState      pgtype.Text        `json:"from_state"`
	ToState        string             `json:"to_state"`
	TransitionedAt pgtype.Timestamptz `json:"transitioned_at"`
	Reason         pgtype.Text        `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type VccFile struct {
	VccFileID      string             `json:"vcc_file_id"`
	LocationID     string             `json:"location_id"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	FileHash       string             `json:"file_hash"`
	RawStorageKey  string             `json:"raw_storage_key"`
	RowCount       int32              `json:"row_count"`
	SourceFilename string             `json:"source_filename"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Status         string             `json:"status"`
}

type VccPaymentGroup struct {
	GroupID                   string             `json:"group_id"`
	VccFileID                 string             `json:"vcc_file_id"`
	LocationID                string             `json:"location_id"`
	TraceID                   string             `json:"trace_id"`
	PaymentID                 string             `json:"payment_id"`
	ProviderNpi               pgtype.Text        `json:"provider_npi"`
	ProviderTaxID             pgtype.Text        `json:"provider_tax_id"`
	CardFingerprint           string             `json:"card_fingerprint"`
	TotalAmount               pgtype.Numeric     `json:"total_amount"`
	Status                    string             `json:"status"`
	IsAuthoritative           bool               `json:"is_authoritative"`
	ReconciliationTriggeredAt pgtype.Timestamptz `json:"reconciliation_triggered_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	FirstReceivedAt           pgtype.Timestamptz `json:"first_received_at"`
	MatchedAt                 pgtype.Timestamptz `json:"matched_at"`
	ExceptionAt               pgtype.Timestamptz `json:"exception_at"`
	PriorStatus               pgtype.Text        `json:"prior_status"`
	ExceptionReason           pgtype.Text        `json:"exception_reason"`
	Version                   int32              `json:"version"`
	PaymentMethodID           pgtype.Text        `json:"payment_method_id"`
}

type VccRow struct {
	RowID             string             `json:"row_id"`
	VccFileID         string             `json:"vcc_file_id"`
	VccPaymentGroupID pgtype.Text        `json:"vcc_payment_group_id"`
	LocationID        string             `json:"location_id"`
	PaymentID         string             `json:"payment_id"`
	TraceID           string             `json:"trace_id"`
	PayerName         pgtype.Text        `json:"payer_name"`
	ProviderNpi       pgtype.Text        `json:"provider_npi"`
	ProviderTaxID     pgtype.Text        `json:"provider_tax_id"`
	IssueDate         pgtype.Date        `json:"issue_date"`
	Amount            pgtype.Numeric     `json:"amount"`
	CardFingerprint   string             `json:"card_fingerprint"`
	Last4             string             `json:"last4"`
	ExpirationDate    pgtype.Text        `json:"expiration_date"`
	PatientID         pgtype.Text        `json:"patient_id"`
	ClaimID           pgtype.Text        `json:"claim_id"`
	ServiceDateStart  pgtype.Date        `json:"service_date_start"`
	ServiceDateEnd    pgtype.Date        `json:"service_date_end"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
