// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processor.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginProcessing = `-- name: BeginProcessing :one
UPDATE reconciled_payments
SET status = 'PROCESSING_PAYMENT',
    idempotency_key = $2,
    processing_started_at = $3,
    updated_at = $3
WHERE reconciled_payment_id = $1
  AND status = 'MATCHED'
RETURNING reconciled_payment_id, location_id, era_payment_group_id, vcc_payment_group_id, trace_number, matched_amount, payer_name, provider_npi, provider_tax_id, status, matched_at, created_at, updated_at, idempotency_key, processor_payment_intent_id, processor_charge_id, processor_error_code, processor_error_message, processing_started_at, processing_completed_at, retry_count
`

type BeginProcessingParams struct {
	ReconciledPaymentID string             `json:"reconciled_payment_id"`
	IdempotencyKey      pgtype.Text        `json:"idempotency_key"`
	ProcessingStartedAt pgtype.Timestamptz `json:"processing_started_at"`
}

func (q *Queries) BeginProcessing(ctx context.Context, arg BeginProcessingParams) (ReconciledPayment, error) {
	row := q.db.QueryRow(ctx, beginProcessing, arg.ReconciledPaymentID, arg.IdempotencyKey, arg.ProcessingStartedAt)
	var i ReconciledPayment
	err := row.Scan(
		&i.ReconciledPaymentID,
		&i.LocationID,
		&i.EraPaymentGroupID,
		&i.VccPaymentGroupID,
		&i.TraceNumber,
		&i.MatchedAmount,
		&i.PayerName,
		&i.ProviderNpi,
		&i.ProviderTaxID,
		&i.Status,
		&i.MatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.ProcessorPaymentIntentID,
		&i.ProcessorChargeID,
		&i.ProcessorErrorCode,
		&i.ProcessorErrorMessage,
		&i.ProcessingStartedAt,
		&i.ProcessingCompletedAt,
		&i.RetryCount,
	)
	return i, err
}

const getMatchedPaymentWithVCCDetails = `-- name: GetMatchedPaymentWithVCCDetails :one
SELECT
    rp.reconciled_payment_id, rp.location_id, rp.era_payment_group_id, rp.vcc_payment_group_id, rp.trace_number, rp.matched_amount, rp.payer_name, rp.provider_npi, rp.provider_tax_id, rp.status, rp.matched_at, rp.created_at, rp.updated_at, rp.idempotency_key, rp.processor_payment_intent_id, rp.processor_charge_id, rp.processor_error_code, rp.processor_error_message, rp.processing_started_at, rp.processing_completed_at, rp.retry_count,
    vpg.version AS vcc_version,
    vpg.card_fingerprint,
    vpg.total_amount,
    vpg.payment_method_id
FROM reconciled_payments rp
JOIN vcc_payment_groups vpg ON vpg.group_id = rp.vcc_payment_group_id
WHERE rp.reconciled_payment_id = $1
LIMIT 1
`

type GetMatchedPaymentWithVCCDetailsRow struct {
	ReconciledPaymentID      string             `json:"reconciled_payment_id"`
	LocationID               string             `json:"location_id"`
	EraPaymentGroupID        string             `json:"era_payment_group_id"`
	VccPaymentGroupID        string             `json:"vcc_payment_group_id"`
	TraceNumber              string             `json:"trace_number"`
	MatchedAmount            pgtype.Numeric     `json:"matched_amount"`
	PayerName                pgtype.Text        `json:"payer_name"`
	ProviderNpi              pgtype.Text        `json:"provider_npi"`
	ProviderTaxID            pgtype.Text        `json:"provider_tax_id"`
	Status                   string             `json:"status"`
	MatchedAt                pgtype.Timestamptz `json:"matched_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	IdempotencyKey           pgtype.Text        `json:"idempotency_key"`
	ProcessorPaymentIntentID pgtype.Text        `json:"processor_payment_intent_id"`
	ProcessorChargeID        pgtype.Text        `json:"processor_charge_id"`
	ProcessorErrorCode       pgtype.Text        `json:"processor_error_code"`
	ProcessorErrorMessage    pgtype.Text        `json:"processor_error_message"`
	ProcessingStartedAt      pgtype.Timestamptz `json:"processing_started_at"`
	ProcessingCompletedAt    pgtype.Timestamptz `json:"processing_completed_at"`
	RetryCount               int32              `json:"retry_count"`
	VccVersion               int32              `json:"vcc_version"`
	CardFingerprint          string             `json:"card_fingerprint"`
	TotalAmount              pgtype.Numeric     `json:"total_amount"`
	PaymentMethodID          pgtype.Text        `json:"payment_method_id"`
}

// PCI BOUNDARY: This query returns the Stripe payment method ID tokenized at ingestion.
// card_number and cvv are never stored or returned; tokenization happened in the ingester.
func (q *Queries) GetMatchedPaymentWithVCCDetails(ctx context.Context, reconciledPaymentID string) (GetMatchedPaymentWithVCCDetailsRow, error) {
	row := q.db.QueryRow(ctx, getMatchedPaymentWithVCCDetails, reconciledPaymentID)
	var i GetMatchedPaymentWithVCCDetailsRow
	err := row.Scan(
		&i.ReconciledPaymentID,
		&i.LocationID,
		&i.EraPaymentGroupID,
		&i.VccPaymentGroupID,
		&i.TraceNumber,
		&i.MatchedAmount,
		&i.PayerName,
		&i.ProviderNpi,
		&i.ProviderTaxID,
		&i.Status,
		&i.MatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.ProcessorPaymentIntentID,
		&i.ProcessorChargeID,
		&i.ProcessorErrorCode,
		&i.ProcessorErrorMessage,
		&i.ProcessingStartedAt,
		&i.ProcessingCompletedAt,
		&i.RetryCount,
		&i.VccVersion,
		&i.CardFingerprint,
		&i.TotalAmount,
		&i.PaymentMethodID,
	)
	return i, err
}

const insertProcessorAttempt = `-- name: InsertProcessorAttempt :one
INSERT INTO processor_attempts (
    attempt_id,
    reconciled_payment_id,
    idempotency_key,
    attempt_number,
    outcome,
    error_code,
    error_message,
    attempted_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING attempt_id, reconciled_payment_id, idempotency_key, attempt_number, outcome, error_code, error_message, attempted_at
`

type InsertProcessorAttemptParams struct {
	AttemptID           string             `json:"attempt_id"`
	ReconciledPaymentID string             `json:"reconciled_payment_id"`
	IdempotencyKey      string             `json:"idempotency_key"`
	AttemptNumber       int32              `json:"attempt_number"`
	Outcome             string             `json:"outcome"`
	ErrorCode           pgtype.Text        `json:"error_code"`
	ErrorMessage        pgtype.Text        `json:"error_message"`
	AttemptedAt         pgtype.Timestamptz `json:"attempted_at"`
}

func (q *Queries) InsertProcessorAttempt(ctx context.Context, arg InsertProcessorAttemptParams) (ProcessorAttempt, error) {
	row := q.db.QueryRow(ctx, insertProcessorAttempt,
		arg.AttemptID,
		arg.ReconciledPaymentID,
		arg.IdempotencyKey,
		arg.AttemptNumber,
		arg.Outcome,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.AttemptedAt,
	)
	var i ProcessorAttempt
	err := row.Scan(
		&i.AttemptID,
		&i.ReconciledPaymentID,
		&i.IdempotencyKey,
		&i.AttemptNumber,
		&i.Outcome,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AttemptedAt,
	)
	return i, err
}

const insertProcessorStateTransition = `-- name: InsertProcessorStateTransition :one
INSERT INTO state_transitions (
    transition_id,
    entity_type,
    entity_id,
    from_state,
    to_state,
    transitioned_at,
    reason
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING transition_id, entity_type, entity_id, from_state, to_state, transitioned_at, reason, created_at
`

type InsertProcessorStateTransitionParams struct {
	TransitionID   string             `json:"transition_id"`
	EntityType     string             `json:"entity_type"`
	EntityID       string             `json:"entity_id"`
	FromState      pgtype.Text        `json:"from_state"`
	ToState        string             `json:"to_state"`
	TransitionedAt pgtype.Timestamptz `json:"transitioned_at"`
	Reason         pgtype.Text        `json:"reason"`
}

func (q *Queries) InsertProcessorStateTransition(ctx context.Context, arg InsertProcessorStateTransitionParams) (StateTransition, error) {
	row := q.db.QueryRow(ctx, insertProcessorStateTransition,
		arg.TransitionID,
		arg.EntityType,
		arg.EntityID,
		arg.FromState,
		arg.ToState,
		arg.TransitionedAt,
		arg.Reason,
	)
	var i StateTransition
	err := row.Scan(
		&i.TransitionID,
		&i.EntityType,
		&i.EntityID,
		&i.FromState,
		&i.ToState,
		&i.TransitionedAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listMatchedPaymentsForProcessing = `-- name: ListMatchedPaymentsForProcessing :many
SELECT reconciled_payment_id, location_id, era_payment_group_id, vcc_payment_group_id, trace_number, matched_amount, payer_name, provider_npi, provider_tax_id, status, matched_at, created_at, updated_at, idempotency_key, processor_payment_intent_id, processor_charge_id, processor_error_code, processor_error_message, processing_started_at, processing_completed_at, retry_count FROM reconciled_payments
WHERE status = 'MATCHED'
ORDER BY matched_at ASC
LIMIT $1
`

func (q *Queries) ListMatchedPaymentsForProcessing(ctx context.Context, limit int32) ([]ReconciledPayment, error) {
	rows, err := q.db.Query(ctx, listMatchedPaymentsForProcessing, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconciledPayment{}
	for rows.Next() {
		var i ReconciledPayment
		if err := rows.Scan(
			&i.ReconciledPaymentID,
			&i.LocationID,
			&i.EraPaymentGroupID,
			&i.VccPaymentGroupID,
			&i.TraceNumber,
			&i.MatchedAmount,
			&i.PayerName,
			&i.ProviderNpi,
			&i.ProviderTaxID,
			&i.Status,
			&i.MatchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdempotencyKey,
			&i.ProcessorPaymentIntentID,
			&i.ProcessorChargeID,
			&i.ProcessorErrorCode,
			&i.ProcessorErrorMessage,
			&i.ProcessingStartedAt,
			&i.ProcessingCompletedAt,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE reconciled_payments
SET status = 'PROCESSING_FAILED',
    processor_error_code = $2,
    processor_error_message = $3,
    retry_count = $4,
    processing_completed_at = $5,
    updated_at = $5
WHERE reconciled_payment_id = $1
RETURNING reconciled_payment_id, location_id, era_payment_group_id, vcc_payment_group_id, trace_number, matched_amount, payer_name, provider_npi, provider_tax_id, status, matched_at, created_at, updated_at, idempotency_key, processor_payment_intent_id, processor_charge_id, processor_error_code, processor_error_message, processing_started_at, processing_completed_at, retry_count
`

type MarkPaymentFailedParams struct {
	ReconciledPaymentID   string             `json:"reconciled_payment_id"`
	ProcessorErrorCode    pgtype.Text        `json:"processor_error_code"`
	ProcessorErrorMessage pgtype.Text        `json:"processor_error_message"`
	RetryCount            int32              `json:"retry_count"`
	ProcessingCompletedAt pgtype.Timestamptz `json:"processing_completed_at"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (ReconciledPayment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed,
		arg.ReconciledPaymentID,
		arg.ProcessorErrorCode,
		arg.ProcessorErrorMessage,
		arg.RetryCount,
		arg.ProcessingCompletedAt,
	)
	var i ReconciledPayment
	err := row.Scan(
		&i.ReconciledPaymentID,
		&i.LocationID,
		&i.EraPaymentGroupID,
		&i.VccPaymentGroupID,
		&i.TraceNumber,
		&i.MatchedAmount,
		&i.PayerName,
		&i.ProviderNpi,
		&i.ProviderTaxID,
		&i.Status,
		&i.MatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.ProcessorPaymentIntentID,
		&i.ProcessorChargeID,
		&i.ProcessorErrorCode,
		&i.ProcessorErrorMessage,
		&i.ProcessingStartedAt,
		&i.ProcessingCompletedAt,
		&i.RetryCount,
	)
	return i, err
}

const markPaymentSucceeded = `-- name: MarkPaymentSucceeded :one
UPDATE reconciled_payments
SET status = 'PAYMENT_SUCCEEDED',
    processor_payment_intent_id = $2,
    processing_completed_at = $3,
    updated_at = $3
WHERE reconciled_payment_id = $1
  AND status = 'PROCESSING_PAYMENT'
RETURNING reconciled_payment_id, location_id, era_payment_group_id, vcc_payment_group_id, trace_number, matched_amount, payer_name, provider_npi, provider_tax_id, status, matched_at, created_at, updated_at, idempotency_key, processor_payment_intent_id, processor_charge_id, processor_error_code, processor_error_message, processing_started_at, processing_completed_at, retry_count
`

type MarkPaymentSucceededParams struct {
	ReconciledPaymentID      string             `json:"reconciled_payment_id"`
	ProcessorPaymentIntentID pgtype.Text        `json:"processor_payment_intent_id"`
	ProcessingCompletedAt    pgtype.Timestamptz `json:"processing_completed_at"`
}

func (q *Queries) MarkPaymentSucceeded(ctx context.Context, arg MarkPaymentSucceededParams) (ReconciledPayment, error) {
	row := q.db.QueryRow(ctx, markPaymentSucceeded, arg.ReconciledPaymentID, arg.ProcessorPaymentIntentID, arg.ProcessingCompletedAt)
	var i ReconciledPayment
	err := row.Scan(
		&i.ReconciledPaymentID,
		&i.LocationID,
		&i.EraPaymentGroupID,
		&i.VccPaymentGroupID,
		&i.TraceNumber,
		&i.MatchedAmount,
		&i.PayerName,
		&i.ProviderNpi,
		&i.ProviderTaxID,
		&i.Status,
		&i.MatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.ProcessorPaymentIntentID,
		&i.ProcessorChargeID,
		&i.ProcessorErrorCode,
		&i.ProcessorErrorMessage,
		&i.ProcessingStartedAt,
		&i.ProcessingCompletedAt,
		&i.RetryCount,
	)
	return i, err
}

const requeueClaimedPayment = `-- name: RequeueClaimedPayment :execrows
UPDATE reconciled_payments
SET status = 'MATCHED',
    processing_started_at = NULL,
    processing_completed_at = NULL,
    updated_at = $2
WHERE reconciled_payment_id = $1
  AND status = 'PROCESSING_PAYMENT'
`

type RequeueClaimedPaymentParams struct {
	ReconciledPaymentID string             `json:"reconciled_payment_id"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RequeueClaimedPayment(ctx context.Context, arg RequeueClaimedPaymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueClaimedPayment, arg.ReconciledPaymentID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
