// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	BeginProcessing(ctx context.Context, arg BeginProcessingParams) (ReconciledPayment, error)
	CreateERAPaymentGroup(ctx context.Context, arg CreateERAPaymentGroupParams) error
	CreateERARemittance(ctx context.Context, arg CreateERARemittanceParams) (EraRemittance, error)
	CreateJobRun(ctx context.Context, arg CreateJobRunParams) (JobRun, error)
	CreateReconciledPayment(ctx context.Context, arg CreateReconciledPaymentParams) (CreateReconciledPaymentRow, error)
	CreateReconcilerJobRun(ctx context.Context, arg CreateReconcilerJobRunParams) (JobRun, error)
	CreateVCCFile(ctx context.Context, arg CreateVCCFileParams) (VccFile, error)
	CreateVCCPaymentGroup(ctx context.Context, arg CreateVCCPaymentGroupParams) error
	ExpireUnmatchedERAPaymentGroup(ctx context.Context, arg ExpireUnmatchedERAPaymentGroupParams) (ExpireUnmatchedERAPaymentGroupRow, error)
	ExpireUnmatchedVCCPaymentGroup(ctx context.Context, arg ExpireUnmatchedVCCPaymentGroupParams) (ExpireUnmatchedVCCPaymentGroupRow, error)
	GetActiveERAPaymentGroup(ctx context.Context, arg GetActiveERAPaymentGroupParams) (GetActiveERAPaymentGroupRow, error)
	GetActiveVCCPaymentGroup(ctx context.Context, arg GetActiveVCCPaymentGroupParams) (GetActiveVCCPaymentGroupRow, error)
	GetERARemittance(ctx context.Context, eraID string) (EraRemittance, error)
	GetERARemittanceByLocationAndHash(ctx context.Context, arg GetERARemittanceByLocationAndHashParams) (EraRemittance, error)
	// PCI BOUNDARY: This query returns the Stripe payment method ID tokenized at ingestion.
	// card_number and cvv are never stored or returned; tokenization happened in the ingester.
	GetMatchedPaymentWithVCCDetails(ctx context.Context, reconciledPaymentID string) (GetMatchedPaymentWithVCCDetailsRow, error)
	GetMatchingERAForVCC(ctx context.Context, arg GetMatchingERAForVCCParams) (GetMatchingERAForVCCRow, error)
	GetMatchingVCCForERA(ctx context.Context, arg GetMatchingVCCForERAParams) (GetMatchingVCCForERARow, error)
	GetVCCFile(ctx context.Context, vccFileID string) (VccFile, error)
	GetVCCFileByLocationAndHash(ctx context.Context, arg GetVCCFileByLocationAndHashParams) (VccFile, error)
	InsertProcessorAttempt(ctx context.Context, arg InsertProcessorAttemptParams) (ProcessorAttempt, error)
	InsertProcessorStateTransition(ctx context.Context, arg InsertProcessorStateTransitionParams) (StateTransition, error)
	InsertReconcilerStateTransition(ctx context.Context, arg InsertReconcilerStateTransitionParams) (StateTransition, error)
	InsertStateTransition(ctx context.Context, arg InsertStateTransitionParams) (StateTransition, error)
	InsertVCCRow(ctx context.Context, arg InsertVCCRowParams) error
	ListERACounterpartCandidates(ctx context.Context, arg ListERACounterpartCandidatesParams) ([]ListERACounterpartCandidatesRow, error)
	ListERARemittancesByReceivedAt(ctx context.Context, limit int32) ([]EraRemittance, error)
	ListEnabledIngestionTargets(ctx context.Context) ([]ListEnabledIngestionTargetsRow, error)
	ListEnabledIngestionTargetsForLocation(ctx context.Context, locationID string) ([]ListEnabledIngestionTargetsForLocationRow, error)
	ListMatchedPaymentsForProcessing(ctx context.Context, limit int32) ([]ReconciledPayment, error)
	ListUnmatchedERAPaymentGroups(ctx context.Context) ([]ListUnmatchedERAPaymentGroupsRow, error)
	ListUnmatchedVCCPaymentGroups(ctx context.Context) ([]ListUnmatchedVCCPaymentGroupsRow, error)
	ListVCCCounterpartCandidates(ctx context.Context, arg ListVCCCounterpartCandidatesParams) ([]ListVCCCounterpartCandidatesRow, error)
	MarkERAPaymentGroupMatched(ctx context.Context, arg MarkERAPaymentGroupMatchedParams) (MarkERAPaymentGroupMatchedRow, error)
	MarkERAReconciliationTriggered(ctx context.Context, groupID string) error
	MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (ReconciledPayment, error)
	MarkPaymentSucceeded(ctx context.Context, arg MarkPaymentSucceededParams) (ReconciledPayment, error)
	MarkVCCGroupNonAuthoritative(ctx context.Context, groupID string) error
	MarkVCCPaymentGroupMatched(ctx context.Context, arg MarkVCCPaymentGroupMatchedParams) (MarkVCCPaymentGroupMatchedRow, error)
	MarkVCCReconciliationTriggered(ctx context.Context, groupID string) error
	NotifyReconciledPaymentMatched(ctx context.Context, pgNotify string) error
	RequeueClaimedPayment(ctx context.Context, arg RequeueClaimedPaymentParams) (int64, error)
	SetERAPaymentGroupException(ctx context.Context, groupID string) error
	SetERARemittanceParseFailure(ctx context.Context, eraID string) error
	SetVCCFileParseFailure(ctx context.Context, arg SetVCCFileParseFailureParams) error
	SetVCCPaymentGroupException(ctx context.Context, groupID string) error
	UpdateERARemittanceParsed(ctx context.Context, arg UpdateERARemittanceParsedParams) error
	UpdateJobRunResult(ctx context.Context, arg UpdateJobRunResultParams) error
	UpdateReconcilerJobRunResult(ctx context.Context, arg UpdateReconcilerJobRunResultParams) error
	UpdateVCCFileParsed(ctx context.Context, arg UpdateVCCFileParsedParams) error
}

var _ Querier = (*Queries)(nil)
