"""
Batch scoring script for the Will They Pay production model.

Loads the flat training table, filters to open invoices, and scores them
using the trained joblib artifact. Writes results to the predictions CSV
that the Go service reads.

Prerequisites:
    1. Run notebooks/production/build_training_data_prod.ipynb
       → produces data/processed/training_data_prod.csv
    2. Run notebooks/production/train_model_prod.ipynb
       → produces models/will_they_pay_prod_v1.joblib

Usage (run from model/):
    python scripts/score_batch.py

    # Custom paths:
    python scripts/score_batch.py \\
        --training-data data/processed/training_data_prod.csv \\
        --model models/will_they_pay_prod_v1.joblib \\
        --output data/output/scored_predictions_prod.csv

Output:
    data/output/scored_predictions_prod.csv
    Columns: personid, postal_code, will_pay_in_30, confidence_score,
             risk_band, model_version, scored_at
"""

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path

import joblib
import pandas as pd

# Open invoice statuses per the payments schema (see docs/db-schemas/payments/)
OPEN_STATUSES = [5, 6, 7, 9]  # PARTIALLY_PAID=5, UNPAID=6, SCHEDULED=7, PENDING=9

MODEL_VERSION = "will_they_pay_prod_v1"


def assign_risk_band(confidence_score: float) -> str:
    """Map confidence score to risk band per the runtime contract."""
    if confidence_score >= 0.70:
        return "high"
    elif confidence_score >= 0.40:
        return "medium"
    else:
        return "low"


def score_batch(
    training_data_path: str,
    model_path: str,
    features_path: str,
    output_path: str,
) -> None:
    # Load model artifacts
    print(f"Loading model: {model_path}")
    model = joblib.load(model_path)

    with open(features_path) as f:
        feature_columns = json.load(f)

    # Load flat training table (generated by build_training_data_prod.ipynb)
    print(f"Loading training data: {training_data_path}")
    df = pd.read_csv(training_data_path)
    print(f"  Total rows loaded: {len(df):,}")

    # Filter to open invoices only
    open_df = df[df["status"].isin(OPEN_STATUSES)].copy()
    print(f"  Open invoice rows:  {len(open_df):,}")

    if len(open_df) == 0:
        print("No open invoices to score. Exiting.")
        return

    # Validate feature columns are present
    missing = [c for c in feature_columns if c not in open_df.columns]
    if missing:
        raise ValueError(
            f"Training data is missing expected feature columns: {missing}\n"
            "Regenerate training_data_prod.csv with build_training_data_prod.ipynb."
        )

    # Score
    X = open_df[feature_columns]
    open_df["will_pay_in_30"] = model.predict(X)
    open_df["confidence_score"] = model.predict_proba(X)[:, 1]
    open_df["risk_band"] = open_df["confidence_score"].apply(assign_risk_band)
    open_df["model_version"] = MODEL_VERSION
    open_df["scored_at"] = datetime.now(timezone.utc).isoformat()

    # Write output
    output_cols = [
        "personid",
        "postal_code",
        "will_pay_in_30",
        "confidence_score",
        "risk_band",
        "model_version",
        "scored_at",
    ]
    output_df = open_df[output_cols]

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    output_df.to_csv(output_path, index=False)

    print(f"\nScored {len(output_df):,} predictions → {output_path}")
    print("\nRisk band distribution:")
    print(output_df["risk_band"].value_counts().to_string())


def main() -> None:
    script_dir = Path(__file__).parent
    model_dir = script_dir.parent / "models"
    data_dir = script_dir.parent / "data"

    parser = argparse.ArgumentParser(
        description="Batch score open invoices using the production Will They Pay model.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--training-data",
        default=str(data_dir / "processed" / "training_data_prod.csv"),
        help="Flat training table from build_training_data_prod.ipynb (default: %(default)s)",
    )
    parser.add_argument(
        "--model",
        default=str(model_dir / "will_they_pay_prod_v1.joblib"),
        help="Trained model artifact (default: %(default)s)",
    )
    parser.add_argument(
        "--features",
        default=str(model_dir / "feature_columns_prod.json"),
        help="Feature column contract JSON (default: %(default)s)",
    )
    parser.add_argument(
        "--output",
        default=str(data_dir / "output" / "scored_predictions_prod.csv"),
        help="Output path for scored predictions (default: %(default)s)",
    )

    args = parser.parse_args()
    score_batch(args.training_data, args.model, args.features, args.output)


if __name__ == "__main__":
    main()
