const exampleAch = {
  file: {
    id: "1542a3afff94fd0e0b83b3685a9d58c31555bc51",
    fileHeader: {
      id: "",
      immediateDestination: "231380104",
      immediateOrigin: "121042882",
      fileCreationDate: "190624",
      fileCreationTime: "0000",
      fileIDModifier: "A",
      FormatCode: "1",
      immediateDestinationName: "Federal Reserve Bank",
      immediateOriginName: "My Bank Name",
      lineNumber: 1,
    },
    batches: [
      {
        batchHeader: {
          id: "",
          serviceClassCode: 225,
          companyName: "Name on Account",
          companyIdentification: "121042882",
          standardEntryClassCode: "PPD",
          companyEntryDescription: "REG.SALARY",
          effectiveEntryDate: "190625",
          settlementDate: "   ",
          originatorStatusCode: 1,
          ODFIIdentification: "12104288",
          batchNumber: 1,
          lineNumber: 2,
        },
        entryDetails: [
          {
            id: "",
            transactionCode: 27,
            RDFIIdentification: "23138010",
            checkDigit: "4",
            DFIAccountNumber: "12345678",
            amount: 100000000,
            identificationNumber: "               ",
            individualName: "Receiver Account Name ",
            discretionaryData: "  ",
            addendaRecordIndicator: 0,
            traceNumber: "121042880000001",
            category: "Forward",
            lineNumber: 3,
          },
        ],
        batchControl: {
          id: "",
          serviceClassCode: 225,
          entryAddendaCount: 1,
          entryHash: 23138010,
          totalDebit: 100000000,
          totalCredit: 0,
          companyIdentification: "121042882",
          ODFIIdentification: "12104288",
          batchNumber: 1,
          lineNumber: 4,
        },
        offset: null,
      },
    ],
    IATBatches: null,
    fileControl: {
      id: "",
      batchCount: 1,
      blockCount: 1,
      entryAddendaCount: 1,
      entryHash: 23138010,
      totalDebit: 100000000,
      totalCredit: 0,
      reserved: "",
      lineNumber: 5,
    },
    fileADVControl: {
      id: "",
      batchCount: 0,
      blockCount: 0,
      entryAddendaCount: 0,
      entryHash: 0,
      totalDebit: 0,
      totalCredit: 0,
    },
    NotificationOfChange: null,
    ReturnEntries: null,
    validateOpts: {
      skipAll: false,
      requireABAOrigin: false,
      bypassOriginValidation: false,
      bypassDestinationValidation: false,
      customTraceNumbers: false,
      allowZeroBatches: false,
      allowMissingFileHeader: false,
      allowMissingFileControl: false,
      bypassCompanyIdentificationMatch: false,
      customReturnCodes: false,
      unequalServiceClassCode: false,
      allowUnorderedBatchNumbers: false,
      allowInvalidCheckDigit: false,
      unequalAddendaCounts: false,
      preserveSpaces: false,
      allowInvalidAmounts: false,
      allowZeroEntryAmount: false,
      allowSpecialCharacters: false,
      allowEmptyIndividualName: false,
      bypassBatchValidation: false,
      skipFileCreationValidation: false,
      skipBatchHeaderCompanyValidation: false,
    },
  },
  error: null,
};
